sudo: false
language: cpp

matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  apt:
    packages:
      - g++-7
    sources: &sources
      - ubuntu-toolchain-r-test

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    # GCC 7
    - os: linux
      env: COMPILER=g++-7 COMPILERGCC=gcc-7 CC=gcc-7 CXX=g++-7
      compiler: gcc
      packages: libcrypto++-dev

script:
  - g++-7 --version
  - g++-7 -c -std=c++17 -Iinclude -Ilib/spdlog/include -Ilib/websocketpp -Ilib/asio/asio/include -Ilib/json/single_include -Ilib/zstr/src src/main.cpp -o main.o
  - g++-7 -c -std=c++17 -Iinclude -Ilib/spdlog/include -Ilib/websocketpp -Ilib/asio/asio/include -Ilib/json/single_include -Ilib/zstr/src src/example.cpp -o example.o
  - g++-7 -o aegis main.o example.o -L/usr/local/ssl/lib -lssl -lpthread -lcrypto -lz -ldl
  - g++-7 -std=c++17 -Iinclude -Ilib/spdlog/include -Ilib/websocketpp -Ilib/asio/asio/include -Ilib/json/single_include -Ilib/zstr/src src/minimal.cpp -lssl -lpthread -lcrypto -lz -ldl -o minimal
