sudo: true
language: cpp

matrix:
  include:
    # GCC 7 C++17
    - os: linux
      compiler: gcc
      env: COMPILER=g++-7 CXX_STANDARD=17
      addons:
        apt:
          packages: libcrypto++-dev g++-7 libasio-dev
          sources: &sources
            - ubuntu-toolchain-r-test
    # GCC 5 C++14
    - os: linux
      compiler: gcc
      env: COMPILER=g++-5 CXX_STANDARD=14
      addons:
        apt:
          packages: libcrypto++-dev g++-5 libasio-dev
          sources: &sources
            - ubuntu-toolchain-r-test

script:
  - ./install-deps.sh
  - mkdir -p build
  - cd build
  - cmake -DBUILD_EXAMPLES=1 -DCMAKE_CXX_COMPILER=${COMPILER} -DCXX_STANDARD=${CXX_STANDARD} ..
  - make
