sudo: false
language: cpp

matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    # GCC 7 C++17
    - os: linux
      compiler: gcc
      packages: libcrypto++-dev g++-7
      env: CXX=g++-7 CXX_STANDARD=17
    # GCC 5 C++14
    - os: linux
      compiler: gcc
      packages: libcrypto++-dev g++-5
      env: CXX=g++-5 CXX_STANDARD=14

script:
  - mkdir -p build
  - cd build
  - cmake -DBUILD_EXAMPLES=1 -DCMAKE_CXX_COMPILER=${CXX} -DCXX_STANDARD=${CXX_STANDARD} ..
  - make
