sudo: true
language: cpp

matrix:
  include:
    # GCC 7 C++17
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="COMPILER=g++-7 && CXX=g++-7 && CXX_STANDARD=17"
      addons:
        apt:
          packages: libcrypto++-dev g++-7
          sources: &sources
            - ubuntu-toolchain-r-test
    # GCC 6 C++14
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="COMPILER=g++-6 && CXX=g++-6 && CXX_STANDARD=14"
      addons:
        apt:
          packages: libcrypto++-dev g++-6
          sources: &sources
            - ubuntu-toolchain-r-test

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - sudo ./install-deps.sh
  - mkdir -p build
  - cd build
  - cmake -DBUILD_EXAMPLES=1 -DCMAKE_CXX_COMPILER=${COMPILER} -DCXX_STANDARD=${CXX_STANDARD} ..
  - make
