sudo: false
language: cpp

matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  apt:
    packages:
      - g++-7
    sources: &sources
      - ubuntu-toolchain-r-test

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    # GCC 7
    - os: linux
      env: COMPILER=g++-7 COMPILERGCC=gcc-7 CC=gcc-7 CXX=g++-7
      compiler: gcc
      packages: libcrypto++-dev

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_EXAMPLES=1 ..
  - make
  - rm -rf *
  - cmake -DBUILD_EXAMPLES=1 -DCMAKE_CXX_COMPILER=g++-7 -DCXX_STANDARD=17 ..
  - make
